spring:
  redis:
    host: localhost

facebook:
  client:
    clientId: 1861225734138705
    clientSecret: ce8b494d284795dcfc806a5cb05492b3
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

kakao :
  client :
    clientId: 5ac1592d79d43524f626d3eb0dc2dfae
    accessTokenUri: https://kauth.kakao.com/oauth/token
    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
  resource:
    userInfoUri: https://kapi.kakao.com/v1/user/me